### ISSUE TITLE
Active class on label is not added

### ISSUE THREAD

**Issue by nicolaslopezj** [djhi/meteor-autoform-materialize#18]
In a update form the "active" class is not added to the label if the value of the input is set. When I focus the input, the label becomes active.

When the form is rendered:
![captura de pantalla 2015-04-24 a las 3 32 33 p m](https://cloud.githubusercontent.com/assets/2042567/7325781/2d8be5f8-ea97-11e4-9971-fcaf5e24f710.png)

When I focus the input:
![captura de pantalla 2015-04-24 a las 3 32 22 p m](https://cloud.githubusercontent.com/assets/2042567/7325777/2909aac4-ea97-11e4-9816-deb198bd9e1e.png)

**Comment by djhi** [comment]
I'll fix that asap, thx for reporting

Le ven. 24 avr. 2015 20:33, Nicolás López notifications@github.com a
écrit :

**Comment by nicolaslopezj** [comment]
Thanks!

**Comment by cpalanzo** [comment]
Still a problem. Any timeline for fix?

**Comment by djhi** [comment]
I won't be able to loot at it before next week. Feel free to submit a pull
request if you can

Le mer. 13 mai 2015 à 07:59, Charlie Palanzo notifications@github.com a
écrit :

**Comment by cpalanzo** [comment]
I'm pretty new to both Meteor and Materialize - and I'm not exactly comfortable changing your code, but I took a quick look and thought it might be simple?

Change This:

```
<template name="afLabel_materialize">
  <label for="{{atts.id}}" {{atts}}>
    {{#if this.labelText}}{{this.labelText}}
    {{else}}{{afFieldLabelText name=this.name}}
    {{/if}}
  </label>
</template>
```

To this?

```
<template name="afLabel_materialize">
  <label for="{{atts.id}}" {{atts}} {{#ifnot this}} class="active" {{/if}}>
    {{#if this.labelText}}{{this.labelText}}
    {{else}}{{afFieldLabelText name=this.name}}
    {{/if}}
  </label>
</template>
```

**Comment by romans127** [comment]
Can we not pass class active through the template it already has a helper for {{atts}}

**Comment by cpalanzo** [comment]
Not really - since the underlying templates are being used by auto-form, or in my case quick-form -- I have no idea if a particular field is populated so I can't make it active.

also my "logic" in the comment above might be reversed.. not sure:
probably should be 

{{#if this}} class="active" {{/if}}

DJHI -- are you still planning to correct this, this week?

**Comment by dandv** [comment]
I found a bug with the `class="active"` for the label in some circumstances: it wouldn't do anything if the input had no value declared _in the HTML_. As a workaround, adding a blank value:

``` html
<input value=" " id="source" type="text" class="validate">
<label class="active" for="source">Source</label>
```

(not sure how this would work with Autoform)

**Comment by cpalanzo** [comment]
Doesn't help with Autoform - still waiting on fix for labels.

**Comment by djhi** [comment]
Apologies to all. I'm working on all tickets right now and will keep you informed

**Comment by otroboe** [comment]
Thanks :+1:

**Comment by nicolaslopezj** [comment]
Thanks!

**Comment by djhi** [comment]
Fixed in 0.0.19, see http://autoform-materialize-playground.meteor.com/. There is a field with a default value which reproduce this.

**Comment by cpalanzo** [comment]
Still have a minor issue. When used on Autoform - the label now moves UP correctly - but OVERLAPS the field above... there is no padding?

**Comment by djhi** [comment]
This should have been fixed too in `0.0.20` by adding a `row` wrapper and `col s12` on the `input-field`

**Comment by docgecko** [comment]
Was this issue resolved? I have the original issue, suggested by @nicolaslopezj, of the label not having the active class when I open up an edit/update form with fields already containing data

**Comment by choyno** [comment]
$('.input-field label').addClass('active');
    setTimeout(function(){ $('.input-field label').addClass('active'); }, 1);
